language: java
before_install:
  - sudo apt-get remove ant
  - wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.gz
  - tar xvfz apache-ant-1.9.4-bin.tar.gz
  - sudo mv apache-ant-1.9.4 /usr/local
  - export ANT_HOME=/usr/local/apache-ant-1.9.4
  - export PATH=$PATH:$ANT_HOME/bin
  - ant -version
jdk:
  - oraclejdk8
script: ant compile
