language: java
before_install:
  - sudo apt-get remove ant
  - wget http://anduin.linuxfromscratch.org/sources/other/junit-4.11.jar
  - wget http://hamcrest.googlecode.com/files/hamcrest-1.3.tgz
  - tar -xvf ../hamcrest-1.3.tgz && cp -v ../junit-4.11.jar \hamcrest-1.3/hamcrest-core-1.3.jar lib/optional
  - ./build.sh -Ddist.dir=/opt/ant-1.9.4 dist && ln -v -sfn ant-1.9.4 /opt/ant
  - export PATH=$PATH:/opt/ant/bin
  - export ANT_HOME=/opt/ant
jdk:
  - oraclejdk8
script: ant compile
