language: java
before_install:
  - su
  - sudo apt-get remove ant
  - cd /opt/
  - sudo wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.0-bin.tar.gz
  - sudo tar xzf apache-ant-1.9.0-bin.tar.gz
  - sudo mv apache-ant-1.9.0 /usr/local/apache-ant
  - sudo echo 'export ANT_HOME=/usr/local/apache-ant' >> /etc/bashrc
  - sudo echo 'export PATH=$PATH:/usr/local/apache-ant/bin' >> /etc/bashrc
  - ant -version
jdk:
  - oraclejdk8
script: ant compile
